services:
  - type: web
    name: esp32-ziaozhi
    runtime: node
    rootDir: backend
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
